// src/utils/fileUtils.js
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Alert, Platform } from "react-native";
import colors from "../theme";

/**
 * Safely convert a value to array
 * @param {any} val
 * @returns {Array}
 */
const toArray = (val) => {
  if (!val) return [];
  if (Array.isArray(val)) return val;
  return [val]; // wrap single value as array
};

/**
 * Format medical history into HTML
 * @param {Object|string} history
 * @returns {string}
 */
const formatMedicalHistory = (history) => {
  if (!history) return "<p>No records available</p>";

  // If stored as JSON string, parse it
  if (typeof history === "string") {
    try {
      history = JSON.parse(history);
    } catch (e) {
      console.warn("Failed to parse medicalHistory JSON:", e);
      return `<p>${history}</p>`; // fallback
    }
  }

  const bloodGroup = history.bloodGroup || "N/A";
  const allergies = toArray(history.allergies);
  const chronicConditions = toArray(history.chronicConditions);
  const medications = toArray(history.medications);

  return `
    <p><strong>Blood Group:</strong> ${bloodGroup}</p>
    <p><strong>Allergies:</strong> ${
      allergies.length > 0 ? allergies.join(", ") : "None"
    }</p>
    <p><strong>Chronic Conditions:</strong> ${
      chronicConditions.length > 0 ? chronicConditions.join(", ") : "None"
    }</p>
    <p><strong>Medications:</strong> ${
      medications.length > 0 ? medications.join(", ") : "None"
    }</p>
  `;
};

/**
 * Generate a PDF patient card and return URI
 * @param {Object} patient - patient object from backend
 * @param {string} formattedDob - patient DOB as YYYY-MM-DD
 * @returns {Promise<string|null>} - URI of generated PDF
 */
export const generatePatientCard = async (patient, formattedDob) => {
  try {
    const htmlContent = `
      <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <style>
            body { font-family: Arial, sans-serif; background: #f5f5f5; padding: 20px; }
            .card { background: ${
              colors.surface
            }; padding: 20px; border-radius: 12px; }
            h1 { color: ${colors.primary}; text-align: center; }
            h2 { color: ${colors.textPrimary}; margin-top: 20px; }
            p { color: ${
              colors.textSecondary
            }; margin: 4px 0; font-size: 14px; }
            hr { border: 0; border-top: 1px solid ${
              colors.border
            }; margin: 10px 0; }
          </style>
        </head>
        <body>
          <div class="card">
            <h1>PATIENT DETAILS</h1>
            <hr />
            <h2>Personal Details</h2>
            <p><strong>Full Name:</strong> ${patient.fullName}</p>
            <p><strong>Patient ID:</strong> ${patient.patientId}</p>
            <p><strong>Date of Birth:</strong> ${formattedDob}</p>
            <p><strong>Sex:</strong> ${patient.sex}</p>
            <p><strong>Phone:</strong> ${patient.phone}</p>
            <p><strong>Email:</strong> ${patient.email}</p>
            <p><strong>Address:</strong> ${patient.address}</p>
            <p><strong>Emergency Contact:</strong> ${
              patient.emergencyContact?.name || "N/A"
            } - ${patient.emergencyContact?.phone || "N/A"}</p>

            <h2>Medical History</h2>
            ${formatMedicalHistory(patient.medicalHistory)}

            <hr />
            <p style="text-align:center; color:${colors.info}; font-size:12px;">
              Generated by SmartHealth System
            </p>
          </div>
        </body>
      </html>
    `;

    const { uri } = await Print.printToFileAsync({
      html: htmlContent,
      base64: false,
    });

    return uri;
  } catch (error) {
    console.error("Generate Patient Card Error:", error);
    Alert.alert("Error", error.message || "Failed to generate patient card.");
    return null;
  }
};

/**
 * Share PDF
 * @param {string} fileUri - URI of the PDF file
 */
export const sharePatientCard = async (fileUri) => {
  if (!fileUri) return;

  try {
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(fileUri, {
        mimeType: "application/pdf",
        dialogTitle: "Share Patient Details",
        UTI: "com.adobe.pdf",
      });
    } else {
      Alert.alert(
        "Sharing Not Available",
        Platform.OS === "web"
          ? "Cannot share PDF on web."
          : "Sharing is not available on this device."
      );
    }
  } catch (error) {
    console.error("Share Error:", error);
    Alert.alert("Error", error.message || "Failed to share patient card.");
  }
};
